name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Api Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: Laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, curl, openssl, pdo, tokenizer, json, xml, ctype, zip

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --no-interaction

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Execute Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_DATABASE: Laravel
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: password
      run: |
        php artisan migrate:fresh --seed
        php artisan test