name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, curl, openssl, pdo, tokenizer, json, xml, ctype, zip

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --no-interaction

    - name: Create environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Execute Tests
      # run: |
      #   sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/g' .env
      #   sed -i 's/DB_HOST=localhost/DB_HOST=mysql/g' .env
      #   sed -i 's/DB_PORT=3306/DB_PORT=3306/g' .env
      #   sed -i 's/DB_DATABASE=Laravel/DB_DATABASE=Laravel/g' .env
      #   sed -i 's/DB_USERNAME=root/DB_USERNAME=root/g' .env
      #   sed -i 's/DB_PASSWORD=password/DB_PASSWORD=password/g' .env
      #   php artisan migrate:fresh --seed
      #   php artisan test
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_DATABASE: Laravel
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: password
      run: |
        php artisan migrate:fresh --seed
        php artisan test