# name: Laravel

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:
#     name: Test
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:5.7
#         env:
#           MYSQL_ROOT_PASSWORD: password
#         ports:
#           - 3306:3306
#         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.3'
#         extensions: mbstring, dom, curl, openssl, pdo, tokenizer, json, xml, ctype, zip

#     - name: Install Composer dependencies
#       run: composer install --no-progress --no-suggest --no-interaction

#     - name: Create environment file
#       run: cp .env.example .env

#     - name: Set up database configuration
#       run: |
#         sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/g' .env
#         sed -i 's/DB_HOST=localhost/DB_HOST=mysql/g' .env
#         sed -i 's/DB_PORT=3306/DB_PORT=3306/g' .env
#         sed -i 's/DB_DATABASE=Laravel/DB_DATABASE=Laravel/g' .env
#         sed -i 's/DB_USERNAME=root/DB_USERNAME=root/g' .env
#         sed -i 's/DB_PASSWORD=password/DB_PASSWORD=password/g' .env

#     - name: Generate application key
#       run: php artisan key:generate

#     - name: Execute Tests
#       env:
#         DB_CONNECTION: mysql
#         DB_HOST: mysql
#         DB_DATABASE: Laravel
#         DB_PORT: 33306
#         DB_USER: root
#         DB_PASSWORD: password
#       run: |
#         php artisan migrate:fresh --seed
#         php artisan test

name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'

    - uses: actions/checkout@v3

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Update Dependencies
      run: composer update

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
  
    - name: Create Database
      run: |
        sudo systemctl start mysql
        sudo mysql --user="root" --password="password"
        mysql 'CREATE DATABASE laravel;'
        mysql 'SHOW DATABASES;'

    - name: Execute migration and seeder
      run: php artisan migrate:refresh --seed

    - name: Install laravel api
      run: php artisan install:api
      
    - name: Execute tests
      run: php artisan test